import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import path from "path";
import runtimeErrorOverlay from "@replit/vite-plugin-runtime-error-modal";
import type { Plugin } from "vite";

const port = Number(process.env.PORT ?? 5173);
const basePath = process.env.BASE_PATH ?? "/";
const apiOrigin = process.env.API_ORIGIN ?? "http://localhost:8080";

/**
 * Sitemap and robots.txt are generated by the API server, but search engines
 * expect them at the storefront root. In dev, this Vite middleware proxies the
 * three SEO assets to the API server. In production, the api-server artifact
 * is configured to also own these paths (see artifact.toml).
 */
function seoProxyPlugin(): Plugin {
  const SEO_PATHS = ["/sitemap.xml", "/sitemap-images.xml", "/robots.txt"];
  return {
    name: "dr-tea-seo-proxy",
    configureServer(server) {
      server.middlewares.use(async (req, res, next) => {
        const url = req.url ?? "";
        const path = url.split("?")[0]!;
        if (!SEO_PATHS.includes(path)) {
          next();
          return;
        }
        try {
          const upstream = await fetch(`${apiOrigin}/api${path}`);
          const text = await upstream.text();
          res.statusCode = upstream.status;
          const ct = upstream.headers.get("content-type");
          if (ct) res.setHeader("Content-Type", ct);
          res.end(text);
        } catch (err) {
          res.statusCode = 502;
          res.end(`SEO proxy error: ${err instanceof Error ? err.message : err}`);
        }
      });
    },
  };
}

export default defineConfig({
  base: basePath,
  plugins: [
    seoProxyPlugin(),
    react(),
    tailwindcss(),
    runtimeErrorOverlay(),
    ...(process.env.NODE_ENV !== "production" &&
    process.env.REPL_ID !== undefined
      ? [
          await import("@replit/vite-plugin-cartographer").then((m) =>
            m.cartographer({
              root: path.resolve(import.meta.dirname, ".."),
            }),
          ),
          await import("@replit/vite-plugin-dev-banner").then((m) =>
            m.devBanner(),
          ),
        ]
      : []),
  ],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "src"),
      "@assets": path.resolve(import.meta.dirname, "..", "..", "attached_assets"),
    },
    dedupe: ["react", "react-dom"],
  },
  root: path.resolve(import.meta.dirname),
  build: {
    outDir: path.resolve(import.meta.dirname, "dist/public"),
    emptyOutDir: true,
  },
  server: {
    port,
    strictPort: true,
    host: "0.0.0.0",
    allowedHosts: true,
    fs: {
      strict: true,
    },
  },
  preview: {
    port,
    host: "0.0.0.0",
    allowedHosts: true,
  },
});
