import {
  pgTable,
  text,
  integer,
  serial,
  jsonb,
  timestamp,
  boolean,
  doublePrecision,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// ──────────────────────────────────────────────────────────────────────────
// Products
// ──────────────────────────────────────────────────────────────────────────

export const productsTable = pgTable("products", {
  id: text("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  category: text("category").notNull(),
  description: text("description").notNull(),
  shortDescription: text("short_description").notNull(),
  price: integer("price").notNull(),
  rating: doublePrecision("rating").notNull().default(0),
  reviewCount: integer("review_count").notNull().default(0),
  variants: jsonb("variants").$type<Array<{ size: string; price: number; stock: number }>>().notNull(),
  tastingNotes: jsonb("tasting_notes").$type<string[]>().notNull().default([]),
  ingredients: jsonb("ingredients").$type<string[]>().notNull().default([]),
  wellnessBenefits: jsonb("wellness_benefits").$type<string[]>().notNull().default([]),
  brewingGuide: jsonb("brewing_guide").$type<{
    temperature: string;
    steepTime: string;
    cupSize: string;
    teaAmount: string;
    steps: string[];
  }>().notNull(),
  origin: text("origin").notNull(),
  harvestSeason: text("harvest_season").notNull(),
  caffeineLevel: text("caffeine_level").notNull(),
  flavorProfile: jsonb("flavor_profile").$type<string[]>().notNull().default([]),
  wellnessFocus: jsonb("wellness_focus").$type<string[]>().notNull().default([]),
  brewingType: text("brewing_type").notNull(),
  ritualStyle: text("ritual_style").notNull(),
  fomoTag: text("fomo_tag"),
  imageUrl: text("image_url").notNull(),
  images: jsonb("images").$type<Array<{
    url: string;
    kind: "hero" | "studio";
    alt?: string;
    isAi?: boolean;
  }>>().notNull().default([]),
  categoryTheme: jsonb("category_theme").$type<{
    primary: string;
    accent: string;
    bg: string;
    gradient: string;
    dark: string;
  }>().notNull().default({
    primary: "330 60% 65%",
    accent: "280 40% 60%",
    bg: "340 30% 96%",
    gradient: "linear-gradient(135deg, hsl(340 30% 96%), hsl(280 30% 96%))",
    dark: "330 40% 20%",
  }),
  pairsWith: jsonb("pairs_with").$type<string[]>().notNull().default([]),
  moodTags: jsonb("mood_tags").$type<string[]>().notNull().default([]),
  plantationStory: text("plantation_story").notNull().default(""),
  sortOrder: integer("sort_order").notNull().default(0),
  metaTitle: text("meta_title").notNull().default(""),
  metaDescription: text("meta_description").notNull().default(""),
  jsonLd: jsonb("json_ld").$type<Record<string, unknown> | null>(),
  relatedProductIds: jsonb("related_product_ids").$type<string[]>().notNull().default([]),
  relatedArticleSlugs: jsonb("related_article_slugs").$type<string[]>().notNull().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertProductSchema = createInsertSchema(productsTable).omit({
  createdAt: true,
  updatedAt: true,
});
export type InsertProduct = z.infer<typeof insertProductSchema>;
export type ProductRow = typeof productsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Journal articles
// ──────────────────────────────────────────────────────────────────────────

export const articlesTable = pgTable("articles", {
  id: serial("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  title: text("title").notNull(),
  excerpt: text("excerpt").notNull(),
  category: text("category").notNull(),
  readTime: text("read_time").notNull(),
  date: text("date").notNull(),
  cover: text("cover").notNull(),
  body: jsonb("body").$type<Array<{ heading?: string; paragraphs: string[] }>>().notNull(),
  published: boolean("published").notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
  metaTitle: text("meta_title").notNull().default(""),
  metaDescription: text("meta_description").notNull().default(""),
  jsonLd: jsonb("json_ld").$type<Record<string, unknown> | null>(),
  relatedProductIds: jsonb("related_product_ids").$type<string[]>().notNull().default([]),
  relatedArticleSlugs: jsonb("related_article_slugs").$type<string[]>().notNull().default([]),
  // Viral social hashtags (#prefix included) and high-intent SEO keywords —
  // generated by the AI meta pass alongside metaTitle/metaDescription.
  hashtags: jsonb("hashtags").$type<string[]>().notNull().default([]),
  seoKeywords: jsonb("seo_keywords").$type<string[]>().notNull().default([]),
  // Community / moderation columns. authorType='admin' covers existing admin
  // articles + AI-generated daily drafts; 'shopper' is a community submission.
  authorType: text("author_type").$type<"admin" | "ai" | "shopper">().notNull().default("admin"),
  authorUserId: text("author_user_id"),
  authorName: text("author_name").notNull().default(""),
  status: text("status").$type<"approved" | "pending" | "rejected">().notNull().default("approved"),
  moderationReason: text("moderation_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ──────────────────────────────────────────────────────────────────────────
// Community: shopper accounts (lightweight email OTP) + journal comments
// ──────────────────────────────────────────────────────────────────────────

export const shopperUsersTable = pgTable("shopper_users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type ShopperUserRow = typeof shopperUsersTable.$inferSelect;

export const shopperSessionsTable = pgTable("shopper_sessions", {
  token: text("token").primaryKey(),
  userId: text("user_id").notNull().references(() => shopperUsersTable.id, { onDelete: "cascade" }),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type ShopperSessionRow = typeof shopperSessionsTable.$inferSelect;

export const shopperOtpsTable = pgTable("shopper_otps", {
  id: serial("id").primaryKey(),
  email: text("email").notNull(),
  code: text("code").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  attempts: integer("attempts").notNull().default(0),
  consumedAt: timestamp("consumed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type ShopperOtpRow = typeof shopperOtpsTable.$inferSelect;

export const journalCommentsTable = pgTable("journal_comments", {
  id: serial("id").primaryKey(),
  articleSlug: text("article_slug").notNull(),
  shopperUserId: text("shopper_user_id").references(() => shopperUsersTable.id, { onDelete: "set null" }),
  authorName: text("author_name").notNull().default(""),
  authorEmail: text("author_email").notNull().default(""),
  body: text("body").notNull(),
  status: text("status").$type<"approved" | "pending" | "rejected">().notNull().default("pending"),
  moderationReason: text("moderation_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type JournalCommentRow = typeof journalCommentsTable.$inferSelect;

export const insertArticleSchema = createInsertSchema(articlesTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertArticle = z.infer<typeof insertArticleSchema>;
export type ArticleRow = typeof articlesTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Orders
// ──────────────────────────────────────────────────────────────────────────

export const ordersTable = pgTable("orders", {
  id: serial("id").primaryKey(),
  customerName: text("customer_name").notNull(),
  customerEmail: text("customer_email").notNull(),
  customerPhone: text("customer_phone"),
  shippingAddress: jsonb("shipping_address").$type<{
    line1: string;
    line2?: string;
    city: string;
    region?: string;
    postalCode: string;
    country: string;
  }>().notNull(),
  currency: text("currency").notNull().default("INR"),
  subtotal: integer("subtotal").notNull(),
  total: integer("total").notNull(),
  status: text("status").notNull().default("pending"),
  notes: text("notes"),
  shopperUserId: text("shopper_user_id"),
  loyaltyPointsEarned: integer("loyalty_points_earned").notNull().default(0),
  loyaltyPointsRedeemed: integer("loyalty_points_redeemed").notNull().default(0),
  loyaltyDiscount: integer("loyalty_discount").notNull().default(0),
  // GST tax invoice number is locked once issued so it satisfies the
  // sequential-within-FY, immutable-after-issue rule under Rule 46.
  invoiceNumber: text("invoice_number").unique(),
  invoiceIssuedAt: timestamp("invoice_issued_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertOrderSchema = createInsertSchema(ordersTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertOrder = z.infer<typeof insertOrderSchema>;
export type OrderRow = typeof ordersTable.$inferSelect;

export const orderItemsTable = pgTable("order_items", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id").notNull().references(() => ordersTable.id, { onDelete: "cascade" }),
  productId: text("product_id").notNull(),
  productName: text("product_name").notNull(),
  variantSize: text("variant_size").notNull(),
  quantity: integer("quantity").notNull(),
  unitPrice: integer("unit_price").notNull(),
  subscription: boolean("subscription").notNull().default(false),
  // Optional per-line HSN + GST rate override — if null we fall back to
  // the seller-wide defaults from business_settings.
  hsnCode: text("hsn_code"),
  gstRatePct: integer("gst_rate_pct"),
});

// ──────────────────────────────────────────────────────────────────────────
// Business Settings (singleton, id=1) — seller GST profile, invoice config
// ──────────────────────────────────────────────────────────────────────────
// Used by every document generator (invoice, packing slip, e-way bill,
// GSTR returns). Singleton row keeps the admin UI a single form.
export const businessSettingsTable = pgTable("business_settings", {
  id: integer("id").primaryKey().default(1),
  legalName: text("legal_name"),
  tradeName: text("trade_name"),
  gstin: text("gstin"),
  pan: text("pan"),
  fssai: text("fssai"),
  cin: text("cin"),
  iec: text("iec"),
  // Registered address — line1/line2 free text, state name + 2-digit code
  // for GST place-of-supply. PIN must be 6 digits.
  address: jsonb("address").$type<{
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    stateCode?: string;
    postalCode?: string;
    country?: string;
  }>().notNull().default(sql`'{}'::jsonb`),
  // Default HSN + GST rate when an order item doesn't override.
  defaultHsnCode: text("default_hsn_code").notNull().default("0902"),
  defaultGstRatePct: integer("default_gst_rate_pct").notNull().default(5),
  // Whether displayed prices are tax-inclusive (Indian retail standard) or
  // exclusive. Affects how we reverse-engineer CGST/SGST/IGST on invoices.
  pricesIncludeTax: boolean("prices_include_tax").notNull().default(true),
  // Invoice numbering: sequential within Indian financial year (Apr-Mar).
  // {fyKey}-NNNNN. fyKey is e.g. "26-27".
  invoicePrefix: text("invoice_prefix").notNull().default("INV"),
  invoiceFyKey: text("invoice_fy_key"),
  invoiceCounter: integer("invoice_counter").notNull().default(0),
  // Bank details for invoice footer (optional).
  bankName: text("bank_name"),
  bankAccountNumber: text("bank_account_number"),
  bankIfsc: text("bank_ifsc"),
  bankBranch: text("bank_branch"),
  upiId: text("upi_id"),
  // Stamp / signature image URL shown on tax invoices.
  signatureImageUrl: text("signature_image_url"),
  invoiceFooterNote: text("invoice_footer_note"),
  // Place of dispatch (warehouse) — falls back to address if blank.
  dispatchAddress: jsonb("dispatch_address").$type<{
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    stateCode?: string;
    postalCode?: string;
  }>().notNull().default(sql`'{}'::jsonb`),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type BusinessSettingsRow = typeof businessSettingsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Nudge Settings (singleton, id=1) — witty popup nudges for hesitant browsers
// ──────────────────────────────────────────────────────────────────────────
// Controls a frontend trigger engine that shows witty / sarcastic / romcom /
// inspirational / hilarious popups to users who browse without buying.
// Admin can toggle the feature, pick allowed tones, tune thresholds, and
// add custom messages on top of the bundled library.
export type NudgeTone =
  | "witty"
  | "sarcastic"
  | "romcom"
  | "inspirational"
  | "hilarious";

export type NudgeTrigger =
  | "idle_browse"        // user has been browsing N seconds without adding to cart
  | "exit_intent"        // mouse moved toward closing the tab (desktop only)
  | "product_dwell"      // dwelled on a product page > N seconds, no add
  | "many_products"      // viewed N+ products, no add
  | "cart_idle"          // has items in cart but hasn't moved to checkout
  | "return_visit";      // came back without buying last time

export type NudgeCustomMessage = {
  id: string;
  tone: NudgeTone;
  trigger: NudgeTrigger;
  text: string;
  cta?: string;
};

export const nudgeSettingsTable = pgTable("nudge_settings", {
  id: integer("id").primaryKey().default(1),
  enabled: boolean("enabled").notNull().default(true),
  // Which tones are allowed. Empty array = all tones.
  tones: jsonb("tones").$type<NudgeTone[]>().notNull().default(sql`'["witty","inspirational","romcom"]'::jsonb`),
  // Which triggers are armed.
  triggers: jsonb("triggers").$type<NudgeTrigger[]>().notNull().default(sql`'["idle_browse","exit_intent","product_dwell","cart_idle"]'::jsonb`),
  // Behavioural thresholds (all in seconds unless noted).
  idleSeconds: integer("idle_seconds").notNull().default(45),
  productDwellSeconds: integer("product_dwell_seconds").notNull().default(25),
  manyProductsThreshold: integer("many_products_threshold").notNull().default(4),
  cartIdleSeconds: integer("cart_idle_seconds").notNull().default(40),
  // Frequency caps to avoid being annoying.
  maxPerSession: integer("max_per_session").notNull().default(2),
  cooldownSeconds: integer("cooldown_seconds").notNull().default(90),
  // Admin-authored extra lines mixed into the library.
  customMessages: jsonb("custom_messages")
    .$type<NudgeCustomMessage[]>()
    .notNull()
    .default(sql`'[]'::jsonb`),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type NudgeSettingsRow = typeof nudgeSettingsTable.$inferSelect;

export const insertOrderItemSchema = createInsertSchema(orderItemsTable).omit({
  id: true,
});
export type InsertOrderItem = z.infer<typeof insertOrderItemSchema>;
export type OrderItemRow = typeof orderItemsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Experiences (Live Theme + Global Experience Switch)
// ──────────────────────────────────────────────────────────────────────────

export type ExperienceBanner = {
  text: string;
  ctaLabel?: string;
  ctaHref?: string;
};

export type ExperienceHeroTakeover = {
  eyebrow?: string;
  title: string;
  subtitle?: string;
  ctaLabel: string;
  ctaHref: string;
  imageUrl?: string;
};

export type ParticleEffect =
  | "none"
  | "rain"
  | "snow"
  | "leaves"
  | "diyas"
  | "petals";

export const experiencesTable = pgTable("experiences", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  themeTokens: jsonb("theme_tokens").$type<Record<string, string>>().notNull().default({}),
  banner: jsonb("banner").$type<ExperienceBanner | null>(),
  heroTakeover: jsonb("hero_takeover").$type<ExperienceHeroTakeover | null>(),
  particleEffect: text("particle_effect").$type<ParticleEffect>().notNull().default("none"),
  isActive: boolean("is_active").notNull().default(false),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertExperienceSchema = createInsertSchema(experiencesTable).omit({
  createdAt: true,
  updatedAt: true,
});
export type InsertExperience = z.infer<typeof insertExperienceSchema>;
export type ExperienceRow = typeof experiencesTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Backups & version history
// ──────────────────────────────────────────────────────────────────────────

export const snapshotsTable = pgTable("snapshots", {
  id: text("id").primaryKey(),
  kind: text("kind").$type<"daily" | "manual">().notNull().default("manual"),
  objectKey: text("object_key").notNull(),
  sizeBytes: integer("size_bytes").notNull().default(0),
  rowCounts: jsonb("row_counts").$type<Record<string, number>>().notNull().default({}),
  status: text("status").$type<"ready" | "failed">().notNull().default("ready"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type SnapshotRow = typeof snapshotsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// SEO ping log (Google / Bing sitemap notifications)
// ──────────────────────────────────────────────────────────────────────────

export const seoPingsTable = pgTable("seo_pings", {
  id: serial("id").primaryKey(),
  target: text("target").$type<"google" | "bing">().notNull(),
  sitemapUrl: text("sitemap_url").notNull(),
  status: text("status").$type<"success" | "failed">().notNull(),
  statusCode: integer("status_code"),
  error: text("error"),
  trigger: text("trigger").notNull().default("auto"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type SeoPingRow = typeof seoPingsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// SEO health snapshots (cached crawl + PageSpeed results)
// ──────────────────────────────────────────────────────────────────────────

export const seoHealthSnapshotsTable = pgTable("seo_health_snapshots", {
  id: serial("id").primaryKey(),
  summary: jsonb("summary").$type<{
    crawledAt?: string;
    crawledUrlCount?: number;
    brokenLinks?: Array<{ from: string; to: string; status: number }>;
    cwv?: Array<{
      url: string;
      strategy: "mobile" | "desktop";
      lcp?: number;
      cls?: number;
      inp?: number;
      performance?: number;
      error?: string;
    }>;
    cwvFetchedAt?: string;
  }>().notNull().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type SeoHealthSnapshotRow = typeof seoHealthSnapshotsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Homepage SEO settings (singleton, id=1)
//
// Lets the admin override the homepage <h1> + sub-line + the trimmed
// meta keywords list + the breadcrumb-home label without redeploying.
// AI-suggest endpoint can repopulate these fields from current catalog
// signals. The dr-tea client falls back to the values hard-coded in
// home.tsx / index.html when the row is empty so the hero never flashes
// blank during initial paint.
// ──────────────────────────────────────────────────────────────────────────

export const homepageSeoSettingsTable = pgTable("homepage_seo_settings", {
  id: integer("id").primaryKey().default(1),
  // The visible H1 line (newlines allowed — rendered with whitespace-pre-line).
  h1Visible: text("h1_visible"),
  // Long-form keyword expansion announced to screen-readers + crawlers.
  h1SrOnly: text("h1_sr_only"),
  // Visible keyword chip line under the H1 (separator-joined).
  h1Subline: text("h1_subline"),
  // Optional eyebrow above the H1 ("Crafted for" by default).
  heroEyebrow: text("hero_eyebrow"),
  // Sub-headline paragraph under the keyword chips.
  heroSubcopy: text("hero_subcopy"),
  // Tag-array applied to <meta name="keywords">. Trim list for SEO hygiene.
  metaKeywords: text("meta_keywords").array().notNull().default(sql`'{}'::text[]`),
  // Breadcrumb root label (default "Home"). Used for both visible UI + JSON-LD.
  breadcrumbHomeLabel: text("breadcrumb_home_label"),
  // When false, Breadcrumbs still render visually but stop emitting JSON-LD.
  breadcrumbsJsonLdEnabled: boolean("breadcrumbs_json_ld_enabled").notNull().default(true),
  // Last AI-suggest run, kept for the admin "last refreshed" hint.
  lastAiSuggestionAt: timestamp("last_ai_suggestion_at", { withTimezone: true }),
  aiNotes: text("ai_notes"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export type HomepageSeoSettingsRow = typeof homepageSeoSettingsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Content Studio (AI social + blog drafts + trend ideas)
// ──────────────────────────────────────────────────────────────────────────

export type ContentChannel =
  | "instagram"
  | "facebook"
  | "twitter"
  | "pinterest"
  | "linkedin"
  | "youtube_shorts"
  | "blog"
  // Auto-Social networks (X / Bluesky / Threads). Same `content_drafts` table,
  // distinguished by this column. Column is plain text in Postgres so adding
  // values is type-only and needs no migration.
  | "x"
  | "bluesky"
  | "threads";

export type ContentKind = "social" | "blog";

// `posting` is a transient lease used by the auto-publish cron + manual
// post-now route to atomically claim a draft before calling the network API,
// preventing double-posts when both fire on the same row concurrently.
export type ContentStatus = "draft" | "approved" | "scheduled" | "posted" | "posting";

export const contentDraftsTable = pgTable("content_drafts", {
  id: serial("id").primaryKey(),
  kind: text("kind").$type<ContentKind>().notNull(),
  channel: text("channel").$type<ContentChannel>().notNull(),
  topic: text("topic").notNull().default(""),
  // For social: caption text. For blog: full markdown body.
  body: text("body").notNull().default(""),
  // Hashtags / tags surfaced as a list (mainly social).
  hashtags: jsonb("hashtags").$type<string[]>().notNull().default([]),
  // Call to action (button label / closing line).
  cta: text("cta").notNull().default(""),
  // Suggested image generation prompt; sent to existing AI image generator.
  imagePrompt: text("image_prompt").notNull().default(""),
  // Stored AI-generated images attached to this draft.
  imageRefs: jsonb("image_refs").$type<Array<{ url: string; alt?: string }>>().notNull().default([]),
  // Blog-only extras (title + JSON-LD + FAQ embedded into body markdown).
  title: text("title").notNull().default(""),
  jsonLd: jsonb("json_ld").$type<Record<string, unknown> | null>(),
  // Original prompt used to generate the draft (for "regenerate").
  prompt: text("prompt").notNull().default(""),
  scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
  // Stamped by the auto-publish cron when status flips to 'posted'.
  postedAt: timestamp("posted_at", { withTimezone: true }),
  status: text("status").$type<ContentStatus>().notNull().default("draft"),
  // Optional link back to the article row created when a blog draft was promoted.
  promotedArticleId: integer("promoted_article_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export const insertContentDraftSchema = createInsertSchema(contentDraftsTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertContentDraft = z.infer<typeof insertContentDraftSchema>;
export type ContentDraftRow = typeof contentDraftsTable.$inferSelect;

export const contentIdeasTable = pgTable("content_ideas", {
  id: serial("id").primaryKey(),
  // Headline / one-line hook.
  headline: text("headline").notNull(),
  // Longer description (1-3 sentences) explaining angle + suggested channel.
  rationale: text("rationale").notNull().default(""),
  // Suggested channels for this idea (e.g. ["instagram","blog"]).
  channels: jsonb("channels").$type<ContentChannel[]>().notNull().default([]),
  // Source keyword / trend / festival the idea sprang from.
  source: text("source").notNull().default(""),
  // Whether the operator has dismissed the idea (kept for history).
  dismissed: boolean("dismissed").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export const insertContentIdeaSchema = createInsertSchema(contentIdeasTable).omit({
  id: true,
  createdAt: true,
});
export type InsertContentIdea = z.infer<typeof insertContentIdeaSchema>;
export type ContentIdeaRow = typeof contentIdeasTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Analytics (Intelligence Hub) — first-party events + cached AI insights.
// ──────────────────────────────────────────────────────────────────────────

export type AnalyticsEventType =
  | "page_view"
  | "product_view"
  | "add_to_cart"
  | "checkout_start"
  | "order_placed";

export const analyticsEventsTable = pgTable("analytics_events", {
  id: serial("id").primaryKey(),
  sessionId: text("session_id").notNull(),
  type: text("type").$type<AnalyticsEventType>().notNull(),
  path: text("path").notNull().default(""),
  // Optional product correlation for product_view / add_to_cart / order_placed.
  productId: text("product_id"),
  // Optional order id for order_placed.
  orderId: integer("order_id"),
  // Monetary value in store base units (rupees / minor unit). Useful for cart
  // and order events.
  value: integer("value"),
  currency: text("currency"),
  // Source attribution captured on first hit of the session.
  referrer: text("referrer").notNull().default(""),
  utmSource: text("utm_source").notNull().default(""),
  utmMedium: text("utm_medium").notNull().default(""),
  utmCampaign: text("utm_campaign").notNull().default(""),
  // Best-effort ISO country code; populated client-side from currency or
  // language guess (we do not run IP geo here).
  country: text("country").notNull().default(""),
  userAgent: text("user_agent").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type AnalyticsEventRow = typeof analyticsEventsTable.$inferSelect;

export const analyticsInsightsTable = pgTable("analytics_insights", {
  id: serial("id").primaryKey(),
  // Date the insights were generated for (UTC date string YYYY-MM-DD).
  forDate: text("for_date").notNull(),
  // Window the AI summarized (in days).
  windowDays: integer("window_days").notNull().default(7),
  // 5 plain-English bullets.
  bullets: jsonb("bullets").$type<string[]>().notNull().default([]),
  // 7-day forecast: array of { date, orders, revenue }.
  forecast: jsonb("forecast").$type<Array<{ date: string; orders: number; revenue: number }>>().notNull().default([]),
  // Snapshot of the assumptions / inputs the forecast used.
  assumptions: jsonb("assumptions").$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type AnalyticsInsightRow = typeof analyticsInsightsTable.$inferSelect;

export const entityVersionsTable = pgTable("entity_versions", {
  id: serial("id").primaryKey(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  action: text("action").$type<"create" | "update" | "delete" | "revert">().notNull(),
  before: jsonb("before"),
  after: jsonb("after"),
  actor: text("actor").notNull().default("admin"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type EntityVersionRow = typeof entityVersionsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Email & Notification Engine (Task #30)
// ──────────────────────────────────────────────────────────────────────────

export type EmailKind =
  | "order_placed"
  | "order_packed"
  | "order_shipped"
  | "order_delivered"
  | "order_refunded"
  | "abandoned_cart"
  | "welcome"
  | "newsletter"
  | "broadcast";

export type EmailStatus = "queued" | "sent" | "failed" | "skipped";

export const emailLogsTable = pgTable("email_logs", {
  id: serial("id").primaryKey(),
  toAddress: text("to_address").notNull(),
  kind: text("kind").$type<EmailKind>().notNull(),
  subject: text("subject").notNull(),
  body: text("body").notNull().default(""),
  campaignId: integer("campaign_id"),
  orderId: integer("order_id"),
  providerMessageId: text("provider_message_id"),
  status: text("status").$type<EmailStatus>().notNull().default("queued"),
  errorMessage: text("error_message"),
  openedAt: timestamp("opened_at", { withTimezone: true }),
  clickedAt: timestamp("clicked_at", { withTimezone: true }),
  trackingToken: text("tracking_token").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type EmailLogRow = typeof emailLogsTable.$inferSelect;

export const newsletterSubscribersTable = pgTable("newsletter_subscribers", {
  id: serial("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name").notNull().default(""),
  source: text("source").notNull().default("storefront"),
  optedInAt: timestamp("opted_in_at", { withTimezone: true }).notNull().defaultNow(),
  unsubscribedAt: timestamp("unsubscribed_at", { withTimezone: true }),
  unsubscribeToken: text("unsubscribe_token").notNull(),
});
export type NewsletterSubscriberRow = typeof newsletterSubscribersTable.$inferSelect;

export const abandonedCartsTable = pgTable("abandoned_carts", {
  id: serial("id").primaryKey(),
  sessionId: text("session_id").notNull(),
  email: text("email").notNull(),
  customerName: text("customer_name").notNull().default(""),
  items: jsonb("items")
    .$type<Array<{ productId: string; productName: string; variantSize: string; quantity: number; unitPrice: number }>>()
    .notNull()
    .default([]),
  subtotal: integer("subtotal").notNull().default(0),
  currency: text("currency").notNull().default("INR"),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
  recoveredAt: timestamp("recovered_at", { withTimezone: true }),
  emailSentAt: timestamp("email_sent_at", { withTimezone: true }),
  resumeToken: text("resume_token").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type AbandonedCartRow = typeof abandonedCartsTable.$inferSelect;

export const pushSubscriptionsTable = pgTable("push_subscriptions", {
  id: serial("id").primaryKey(),
  endpoint: text("endpoint").notNull().unique(),
  p256dh: text("p256dh").notNull(),
  authKey: text("auth_key").notNull(),
  userAgent: text("user_agent").notNull().default(""),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type PushSubscriptionRow = typeof pushSubscriptionsTable.$inferSelect;

export type CampaignStatus = "draft" | "sending" | "sent" | "failed";
export type CampaignChannel = "email" | "push";

export const marketingCampaignsTable = pgTable("marketing_campaigns", {
  id: serial("id").primaryKey(),
  channel: text("channel").$type<CampaignChannel>().notNull().default("email"),
  subject: text("subject").notNull(),
  preheader: text("preheader").notNull().default(""),
  body: text("body").notNull(),
  ctaLabel: text("cta_label").notNull().default(""),
  ctaUrl: text("cta_url").notNull().default(""),
  audience: text("audience").notNull().default("all"),
  status: text("status").$type<CampaignStatus>().notNull().default("draft"),
  recipientsCount: integer("recipients_count").notNull().default(0),
  sentCount: integer("sent_count").notNull().default(0),
  openCount: integer("open_count").notNull().default(0),
  clickCount: integer("click_count").notNull().default(0),
  errorMessage: text("error_message"),
  scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type MarketingCampaignRow = typeof marketingCampaignsTable.$inferSelect;
export const insertMarketingCampaignSchema = createInsertSchema(marketingCampaignsTable).omit({
  id: true,
  createdAt: true,
  sentAt: true,
  recipientsCount: true,
  sentCount: true,
  openCount: true,
  clickCount: true,
  errorMessage: true,
});
export type InsertMarketingCampaign = z.infer<typeof insertMarketingCampaignSchema>;

// ──────────────────────────────────────────────────────────────────────────
// Campaign Orchestrator (multi-channel campaign bundles)
// ──────────────────────────────────────────────────────────────────────────

export type CampaignBundleStatus = "draft" | "approved" | "scheduled" | "live" | "archived";

export interface AdCreative {
  headline: string;
  description: string;
  imagePrompt: string;
  imageUrl?: string;
}

export const campaignsTable = pgTable("campaigns", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  brief: text("brief").notNull().default(""),
  moment: text("moment").notNull().default(""),
  status: text("status").$type<CampaignBundleStatus>().notNull().default("draft"),
  targetProductIds: jsonb("target_product_ids").$type<string[]>().notNull().default([]),
  // Proposed bundle (editable before approval). Snapshot of the AI output
  // so an operator can iterate without re-calling the model.
  proposed: jsonb("proposed").$type<{
    experience?: {
      name: string;
      themeTokens?: Record<string, string>;
      banner?: ExperienceBanner | null;
      heroTakeover?: ExperienceHeroTakeover | null;
      particleEffect?: ParticleEffect;
    };
    blog?: { title: string; body: string; imagePrompt: string; cta: string; hashtags: string[] };
    socials?: Array<{ channel: ContentChannel; body: string; hashtags: string[]; cta: string; imagePrompt: string }>;
    email?: { subject: string; preheader: string; body: string; ctaLabel: string; ctaUrl: string };
    adCreatives?: AdCreative[];
  } | null>(),
  // After approval — references to the rows we created.
  experienceId: text("experience_id"),
  blogDraftId: integer("blog_draft_id"),
  socialDraftIds: jsonb("social_draft_ids").$type<number[]>().notNull().default([]),
  emailCampaignId: integer("email_campaign_id"),
  adCreatives: jsonb("ad_creatives").$type<AdCreative[]>().notNull().default([]),
  scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export type CampaignRow = typeof campaignsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Keyword + competitor watch
// ──────────────────────────────────────────────────────────────────────────

export const keywordsTable = pgTable("keywords", {
  id: serial("id").primaryKey(),
  term: text("term").notNull().unique(),
  market: text("market").notNull().default("IN"),
  // Last AI-summary text rolled up from the recent rank deltas (weekly).
  lastSummary: text("last_summary").notNull().default(""),
  lastSummaryAt: timestamp("last_summary_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type KeywordRow = typeof keywordsTable.$inferSelect;

export const keywordRanksTable = pgTable("keyword_ranks", {
  id: serial("id").primaryKey(),
  keywordId: integer("keyword_id").notNull(),
  // null position = "not in top 100" or shadow-mode skipped (when no SERP API key).
  position: integer("position"),
  url: text("url").notNull().default(""),
  source: text("source").notNull().default("shadow"),
  checkedAt: timestamp("checked_at", { withTimezone: true }).notNull().defaultNow(),
});
export type KeywordRankRow = typeof keywordRanksTable.$inferSelect;

// Singleton: which SERP provider the keyword cron should use. API keys for
// each provider stay in env secrets (SERPAPI_KEY, SERPER_API_KEY, etc.) —
// only the *choice* lives in the DB so admins can switch without a redeploy.
export const keywordRankProviderTable = pgTable("keyword_rank_provider", {
  id: serial("id").primaryKey(),
  // 'serpapi' | 'serper' | 'searchapi' | 'valueserp'
  provider: text("provider").notNull().default("serpapi"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export type KeywordRankProviderRow = typeof keywordRankProviderTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Payment gateway settings (single-row KV; sensitive keys stay in env)
// ──────────────────────────────────────────────────────────────────────────

export const paymentSettingsTable = pgTable("payment_settings", {
  id: serial("id").primaryKey(),
  // active provider key: "razorpay" | "stripe" | "cashfree" | "phonepe" | "none"
  activeProvider: text("active_provider").notNull().default("razorpay"),
  codEnabled: boolean("cod_enabled").notNull().default(true),
  // Optional storefront-facing copy
  codLabel: text("cod_label").notNull().default("Cash on Delivery"),
  paidLabel: text("paid_label").notNull().default("UPI / Card / Netbanking"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export type PaymentSettingsRow = typeof paymentSettingsTable.$inferSelect;

export const teapediaEntriesTable = pgTable("teapedia_entries", {
  id: serial("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  title: text("title").notNull(),
  summary: text("summary").notNull(),
  category: text("category").notNull().default("Types"),
  tags: jsonb("tags").$type<string[]>().notNull().default([]),
  hero: text("hero").notNull().default(""),
  body: jsonb("body").$type<Array<{ heading?: string; paragraphs: string[] }>>().notNull().default([]),
  relatedProductIds: jsonb("related_product_ids").$type<string[]>().notNull().default([]),
  relatedCategorySlugs: jsonb("related_category_slugs").$type<string[]>().notNull().default([]),
  relatedEntrySlugs: jsonb("related_entry_slugs").$type<string[]>().notNull().default([]),
  metaTitle: text("meta_title").notNull().default(""),
  metaDescription: text("meta_description").notNull().default(""),
  jsonLd: jsonb("json_ld").$type<Record<string, unknown> | null>(),
  authorType: text("author_type").$type<"admin" | "ai">().notNull().default("ai"),
  status: text("status").$type<"approved" | "pending" | "rejected">().notNull().default("pending"),
  published: boolean("published").notNull().default(false),
  sortOrder: integer("sort_order").notNull().default(0),
  viewCount: integer("view_count").notNull().default(0),
  moderationReason: text("moderation_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export type TeapediaEntryRow = typeof teapediaEntriesTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Content Hub — long-form editorial across three sub-sections:
//   pairing   → "Best tea with chocolate cake", pairing guides
//   wellness  → Ayurveda / sleep / immunity / caffeine-free guides
//   regional  → Kolkata chai, Kashmiri kahwa, Irani chai, Tibetan butter tea
// One table, one admin, one cron, three storefront destinations.
// ──────────────────────────────────────────────────────────────────────────

export type ContentHubKind = "pairing" | "wellness" | "regional";

export const contentHubEntriesTable = pgTable("content_hub_entries", {
  id: serial("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  hub: text("hub").$type<ContentHubKind>().notNull(),
  title: text("title").notNull(),
  summary: text("summary").notNull(),
  category: text("category").notNull().default(""),
  tags: jsonb("tags").$type<string[]>().notNull().default([]),
  hero: text("hero").notNull().default(""),
  body: jsonb("body")
    .$type<Array<{ heading?: string; paragraphs: string[] }>>()
    .notNull()
    .default([]),
  // Optional structured side-cards rendered on detail pages.
  // pairing: { teas: string[], notes: string }
  // wellness: { useFor: string[], brewMinutes?: number, caffeine?: "none"|"low"|"medium"|"high" }
  // regional: { region: string, since?: string, brewedWith?: string[] }
  facets: jsonb("facets").$type<Record<string, unknown> | null>(),
  faqs: jsonb("faqs").$type<Array<{ q: string; a: string }>>().notNull().default([]),
  relatedProductIds: jsonb("related_product_ids").$type<string[]>().notNull().default([]),
  relatedRecipeSlugs: jsonb("related_recipe_slugs").$type<string[]>().notNull().default([]),
  relatedEntrySlugs: jsonb("related_entry_slugs").$type<string[]>().notNull().default([]),
  metaTitle: text("meta_title").notNull().default(""),
  metaDescription: text("meta_description").notNull().default(""),
  jsonLd: jsonb("json_ld").$type<Record<string, unknown> | null>(),
  authorType: text("author_type").$type<"admin" | "ai">().notNull().default("ai"),
  status: text("status").$type<"approved" | "pending" | "rejected">().notNull().default("pending"),
  published: boolean("published").notNull().default(false),
  sortOrder: integer("sort_order").notNull().default(0),
  viewCount: integer("view_count").notNull().default(0),
  moderationReason: text("moderation_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export type ContentHubEntryRow = typeof contentHubEntriesTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Franchise applications — public lead capture (no auth)
// ──────────────────────────────────────────────────────────────────────────

export const franchiseApplicationsTable = pgTable("franchise_applications", {
  id: serial("id").primaryKey(),
  fullName: text("full_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  city: text("city").notNull(),
  state: text("state").notNull().default(""),
  investmentRange: text("investment_range").notNull(), // "10-25L" | "25-50L" | "50L-1Cr" | "1Cr+"
  preferredFormat: text("preferred_format").notNull().default("kiosk"), // "kiosk" | "cafe" | "flagship"
  experience: text("experience").notNull().default(""), // free-text retail/F&B experience
  message: text("message").notNull().default(""),
  status: text("status").$type<"new" | "contacted" | "qualified" | "rejected" | "signed">().notNull().default("new"),
  source: text("source").notNull().default("website"),
  ipAddress: text("ip_address").notNull().default(""),
  userAgent: text("user_agent").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export type FranchiseApplicationRow = typeof franchiseApplicationsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Wholesale / B2B leads — bulk supply enquiries from cafes, hotels, offices,
// corporate gifting buyers, and reseller boutiques. Distinct from franchise
// (those open Dr Tea outlets); these buyers buy tea wholesale.
// ──────────────────────────────────────────────────────────────────────────

export type WholesaleSegment =
  | "cafe"
  | "hotel"
  | "office"
  | "gifting"
  | "retailer"
  | "other";

export type WholesaleVolume =
  | "under-25kg"
  | "25-100kg"
  | "100-500kg"
  | "500kg-plus";

export type WholesaleStatus =
  | "new"
  | "contacted"
  | "quoted"
  | "won"
  | "lost";

export const wholesaleLeadsTable = pgTable("wholesale_leads", {
  id: serial("id").primaryKey(),
  companyName: text("company_name").notNull(),
  contactName: text("contact_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  city: text("city").notNull(),
  state: text("state").notNull().default(""),
  segment: text("segment").$type<WholesaleSegment>().notNull().default("cafe"),
  monthlyVolume: text("monthly_volume").$type<WholesaleVolume>().notNull().default("under-25kg"),
  interestedIn: jsonb("interested_in").$type<string[]>().notNull().default([]),
  message: text("message").notNull().default(""),
  status: text("status").$type<WholesaleStatus>().notNull().default("new"),
  source: text("source").notNull().default("website"),
  ipAddress: text("ip_address").notNull().default(""),
  userAgent: text("user_agent").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export type WholesaleLeadRow = typeof wholesaleLeadsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Mission Control: a single AI-generated daily briefing (wins/risks/action)
// keyed by date. The cron pre-generates today's briefing; admins can also
// trigger an on-demand refresh. We retain the last ~90 rows for history.
// ──────────────────────────────────────────────────────────────────────────
export const missionBriefingsTable = pgTable("mission_briefings", {
  id: serial("id").primaryKey(),
  forDate: text("for_date").notNull().unique(), // YYYY-MM-DD (UTC)
  wins: jsonb("wins").$type<string[]>().notNull().default([]),
  risks: jsonb("risks").$type<string[]>().notNull().default([]),
  action: text("action").notNull().default(""),
  headline: text("headline").notNull().default(""),
  model: text("model").notNull().default(""),
  inputSnapshot: jsonb("input_snapshot")
    .$type<Record<string, unknown>>()
    .notNull()
    .default({}),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type MissionBriefingRow = typeof missionBriefingsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Loyalty: simple points (1 point per ₹10 spent) tied to shopper accounts.
// One account row per shopper; immutable ledger entries record every credit
// (earn) and debit (redeem) so the running balance is always reconcilable.
// ──────────────────────────────────────────────────────────────────────────

export const loyaltyAccountsTable = pgTable("loyalty_accounts", {
  shopperUserId: text("shopper_user_id")
    .primaryKey()
    .references(() => shopperUsersTable.id, { onDelete: "cascade" }),
  pointsBalance: integer("points_balance").notNull().default(0),
  lifetimePoints: integer("lifetime_points").notNull().default(0),
  lifetimeSpend: integer("lifetime_spend").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export type LoyaltyAccountRow = typeof loyaltyAccountsTable.$inferSelect;

export type LoyaltyLedgerKind = "earn" | "redeem" | "adjust";

export const loyaltyLedgerTable = pgTable("loyalty_ledger", {
  id: serial("id").primaryKey(),
  shopperUserId: text("shopper_user_id")
    .notNull()
    .references(() => shopperUsersTable.id, { onDelete: "cascade" }),
  kind: text("kind").$type<LoyaltyLedgerKind>().notNull(),
  points: integer("points").notNull(),
  orderId: integer("order_id"),
  note: text("note").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type LoyaltyLedgerRow = typeof loyaltyLedgerTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Gift cards: prepaid balance instruments. A purchase mints a card with a
// unique code; the bearer redeems it at checkout (partial redemptions OK).
// All amounts in rupees (matches ordersTable convention). One row per
// redemption recorded for audit + reporting.
// ──────────────────────────────────────────────────────────────────────────

export type GiftCardStatus = "active" | "redeemed" | "cancelled" | "expired";

// Physical-only fulfilment lifecycle. Digital cards stay at "na" forever.
export type GiftCardPhysicalStatus =
  | "na"
  | "pending"
  | "printed"
  | "shipped"
  | "delivered";

export type GiftCardFormat = "digital" | "physical";

export interface GiftCardPersonalization {
  recipientPhotoUrl?: string;
  calligraphyName?: string;
  signature?: string;
  occasionTag?: string;
  voiceNoteUrl?: string;
}

export interface GiftCardDeliveryAddress {
  fullName: string;
  phone: string;
  street1: string;
  street2?: string;
  city: string;
  state: string;
  pincode: string;
  country: string;
  landmark?: string;
}

export const giftCardsTable = pgTable("gift_cards", {
  id: serial("id").primaryKey(),
  code: text("code").notNull().unique(),
  initialAmount: integer("initial_amount").notNull(),
  balance: integer("balance").notNull(),
  currency: text("currency").notNull().default("INR"),
  status: text("status").$type<GiftCardStatus>().notNull().default("active"),
  purchaserUserId: text("purchaser_user_id"),
  purchaserEmail: text("purchaser_email").notNull().default(""),
  recipientName: text("recipient_name").notNull().default(""),
  recipientEmail: text("recipient_email").notNull().default(""),
  senderName: text("sender_name").notNull().default(""),
  message: text("message").notNull().default(""),
  purchaseOrderId: integer("purchase_order_id"),
  paymentRef: text("payment_ref").notNull().default(""),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  // Premium / physical extension ─────────────────────────────────
  format: text("format").$type<GiftCardFormat>().notNull().default("digital"),
  designId: text("design_id").notNull().default("classic-evergreen"),
  packagingId: text("packaging_id").notNull().default("digital"),
  packagingFee: integer("packaging_fee").notNull().default(0),
  personalization: jsonb("personalization")
    .$type<GiftCardPersonalization | null>()
    .default(null),
  deliveryAddress: jsonb("delivery_address")
    .$type<GiftCardDeliveryAddress | null>()
    .default(null),
  scheduledDeliveryAt: timestamp("scheduled_delivery_at", { withTimezone: true }),
  physicalStatus: text("physical_status")
    .$type<GiftCardPhysicalStatus>()
    .notNull()
    .default("na"),
  physicalTrackingUrl: text("physical_tracking_url").notNull().default(""),
  physicalCourier: text("physical_courier").notNull().default(""),
  physicalAwb: text("physical_awb").notNull().default(""),
  physicalNotes: text("physical_notes").notNull().default(""),
  // Membership / luxury extension ───────────────────────────────
  // tier is auto-assigned from cumulative load value; once promoted, the
  // card never demotes (a Gold member who spends down stays Gold).
  tier: text("tier").$type<GiftCardTier>().notNull().default("standard"),
  // Hand-numbered, human-readable. Format: "DT/<YEAR>/<6-digit zero-padded>".
  // Embossed on the physical card and printed on the digital share.
  serial: text("serial").notNull().default(""),
  // Cumulative loads + redemptions (excluding bonus credit) so we can
  // compute lifetime spend and tier promotions without re-walking
  // redemption rows.
  lifetimeLoaded: integer("lifetime_loaded").notNull().default(0),
  lifetimeRedeemed: integer("lifetime_redeemed").notNull().default(0),
  // Bonus credit issued on this card (free top-up bonuses, birthday
  // credits, anniversary stipend). Lives inside `balance` but tracked
  // separately for accounting + receipt display.
  bonusCredit: integer("bonus_credit").notNull().default(0),
  // Number of successful top-ups (purchase counts as #0). Surfaced to
  // shoppers as "loaded N times" — small social proof.
  topupCount: integer("topup_count").notNull().default(0),
  lastToppedUpAt: timestamp("last_topped_up_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export type GiftCardTier = "standard" | "silver" | "gold" | "obsidian";
export type GiftCardRow = typeof giftCardsTable.$inferSelect;

export const giftCardRedemptionsTable = pgTable("gift_card_redemptions", {
  id: serial("id").primaryKey(),
  giftCardId: integer("gift_card_id")
    .notNull()
    .references(() => giftCardsTable.id, { onDelete: "cascade" }),
  orderId: integer("order_id").notNull(),
  amount: integer("amount").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type GiftCardRedemptionRow = typeof giftCardRedemptionsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Subscriptions: a shopper opts in to a recurring delivery for a specific
// product+variant. We track nextDeliveryAt + status + frequency so the
// shopper can pause/skip/resume/cancel from /account; the actual recurring
// charge is left for a future Razorpay-Subscriptions / cron worker phase.
// ──────────────────────────────────────────────────────────────────────────

export type SubscriptionStatus = "active" | "paused" | "cancelled";

export const subscriptionsTable = pgTable("subscriptions", {
  id: serial("id").primaryKey(),
  shopperUserId: text("shopper_user_id")
    .notNull()
    .references(() => shopperUsersTable.id, { onDelete: "cascade" }),
  productId: text("product_id").notNull(),
  productName: text("product_name").notNull().default(""),
  variantSize: text("variant_size").notNull(),
  quantity: integer("quantity").notNull().default(1),
  unitPrice: integer("unit_price").notNull(),
  currency: text("currency").notNull().default("INR"),
  frequencyWeeks: integer("frequency_weeks").notNull().default(4),
  discountPct: integer("discount_pct").notNull().default(10),
  status: text("status").$type<SubscriptionStatus>().notNull().default("active"),
  nextDeliveryAt: timestamp("next_delivery_at", { withTimezone: true }).notNull(),
  lastOrderId: integer("last_order_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export type SubscriptionRow = typeof subscriptionsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Product reviews. One review per (shopperUserId, productId). verifiedPurchase
// is computed at write time by checking the shopper's order_items. status
// gates whether the review appears publicly — defaults to "approved" so we
// don't need a moderation backlog on day one, but flagged content can be
// hidden by an admin update later.
// ──────────────────────────────────────────────────────────────────────────

export type ReviewStatus = "approved" | "pending" | "hidden";

export const productReviewsTable = pgTable(
  "product_reviews",
  {
    id: serial("id").primaryKey(),
    productId: text("product_id").notNull(),
    shopperUserId: text("shopper_user_id")
      .notNull()
      .references(() => shopperUsersTable.id, { onDelete: "cascade" }),
    rating: integer("rating").notNull(),
    title: text("title").notNull().default(""),
    body: text("body").notNull(),
    verifiedPurchase: boolean("verified_purchase").notNull().default(false),
    helpfulCount: integer("helpful_count").notNull().default(0),
    status: text("status").$type<ReviewStatus>().notNull().default("approved"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    uniqueShopperProduct: uniqueIndex("product_reviews_shopper_product_uq").on(
      t.shopperUserId,
      t.productId,
    ),
  }),
);
export type ProductReviewRow = typeof productReviewsTable.$inferSelect;

// Per-shopper helpful votes. Enforces "one helpful vote per shopper per
// review" at the DB layer so client-side dedupe is no longer the source of
// truth and bots can't inflate counts.
export const reviewHelpfulVotesTable = pgTable(
  "review_helpful_votes",
  {
    id: serial("id").primaryKey(),
    reviewId: integer("review_id")
      .notNull()
      .references(() => productReviewsTable.id, { onDelete: "cascade" }),
    shopperUserId: text("shopper_user_id")
      .notNull()
      .references(() => shopperUsersTable.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    uniqueVote: uniqueIndex("review_helpful_votes_uq").on(t.reviewId, t.shopperUserId),
  }),
);
export type ReviewHelpfulVoteRow = typeof reviewHelpfulVotesTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Recipes — tea-led recipes (chai variations, iced teas, kadhas, lattes,
// desserts) that link out to the products needed to brew them.
// Mirrors the teapedia/journal content shape: jsonb body + media metadata,
// published flag, view count for popularity ranking.
// ──────────────────────────────────────────────────────────────────────────

export type RecipeDifficulty = "easy" | "medium" | "hard";

export const recipesTable = pgTable("recipes", {
  id: serial("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  title: text("title").notNull(),
  summary: text("summary").notNull(),
  hero: text("hero").notNull().default(""),
  category: text("category").notNull().default("Chai"),
  tags: jsonb("tags").$type<string[]>().notNull().default([]),
  difficulty: text("difficulty").$type<RecipeDifficulty>().notNull().default("easy"),
  prepMinutes: integer("prep_minutes").notNull().default(5),
  cookMinutes: integer("cook_minutes").notNull().default(10),
  servings: integer("servings").notNull().default(2),
  ingredients: jsonb("ingredients").$type<Array<{ name: string; amount: string; note?: string }>>().notNull().default([]),
  steps: jsonb("steps").$type<Array<{ title?: string; body: string }>>().notNull().default([]),
  tips: jsonb("tips").$type<string[]>().notNull().default([]),
  relatedProductIds: jsonb("related_product_ids").$type<string[]>().notNull().default([]),
  // Persona byline — fictional Dr Tea customer who "submitted" the recipe.
  authorName: text("author_name").notNull().default(""),
  authorAvatar: text("author_avatar").notNull().default(""),
  authorLocation: text("author_location").notNull().default(""),
  authorQuote: text("author_quote").notNull().default(""),
  // Country / region of origin for worldwide tea recipes.
  origin: text("origin").notNull().default(""),
  // Story-mode slides — Instagram-story style swipe through the recipe.
  storyMode: jsonb("story_mode")
    .$type<Array<{ image: string; title?: string; caption: string }>>()
    .notNull()
    .default([]),
  // Viral social hashtags (#prefix included) and high-intent SEO keywords.
  hashtags: jsonb("hashtags").$type<string[]>().notNull().default([]),
  seoKeywords: jsonb("seo_keywords").$type<string[]>().notNull().default([]),
  // Provenance + workflow flags for the AI recipe drafter.
  authorType: text("author_type").$type<"manual" | "ai">().notNull().default("manual"),
  status: text("status").$type<"pending" | "approved" | "rejected">().notNull().default("approved"),
  metaTitle: text("meta_title").notNull().default(""),
  metaDescription: text("meta_description").notNull().default(""),
  published: boolean("published").notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
  viewCount: integer("view_count").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});
export type RecipeRow = typeof recipesTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Admin alerts state — singleton row tracking when the operator last saw
// the alerts panel and which alert keys they've explicitly dismissed.
// Alerts themselves are computed at request-time from live store data.
// ──────────────────────────────────────────────────────────────────────────

export const adminAlertStateTable = pgTable("admin_alert_state", {
  id: text("id").primaryKey().default("singleton"),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  dismissed: jsonb("dismissed")
    .$type<Record<string, string>>()
    .notNull()
    .default({}),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type AdminAlertStateRow = typeof adminAlertStateTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Co-pilot agent audit log — one row per executed plan. Captures the
// original natural-language query, the proposed plan (array of tool calls),
// the per-step results, and overall status so operators can review what
// the AI actually did on their behalf.
// ──────────────────────────────────────────────────────────────────────────

export type CopilotPlanStatus = "running" | "success" | "partial" | "failed";

export interface CopilotToolCall {
  name: string;
  description?: string;
  params: Record<string, unknown>;
}

export interface CopilotToolResult {
  name: string;
  ok: boolean;
  message?: string;
  data?: unknown;
}

export const adminCopilotActionLogTable = pgTable("admin_copilot_action_log", {
  id: serial("id").primaryKey(),
  query: text("query").notNull().default(""),
  plan: jsonb("plan").$type<CopilotToolCall[]>().notNull().default([]),
  results: jsonb("results").$type<CopilotToolResult[]>().notNull().default([]),
  status: text("status").$type<CopilotPlanStatus>().notNull().default("running"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
});
export type AdminCopilotActionLogRow =
  typeof adminCopilotActionLogTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Generic admin activity / audit feed.
//
// One row per write action performed against the admin surface. Sources
// include the co-pilot's executed plans, alert dismissals, order status
// changes, article publishing, product edits, and so on. The dedicated
// admin_copilot_action_log keeps the deep per-step plan detail; this table
// is the unified feed an operator scans to answer "who/what changed
// recently?".
// ──────────────────────────────────────────────────────────────────────────

export type ActivityKind =
  | "copilot_plan"
  | "alert_seen"
  | "alert_dismissed"
  | "order_status_changed"
  | "order_updated"
  | "article_created"
  | "article_updated"
  | "article_published"
  | "article_unpublished"
  | "article_deleted"
  | "product_created"
  | "product_updated"
  | "product_deleted"
  | "customer_note_added"
  | "team_member_invited"
  | "team_member_updated"
  | "team_member_revoked"
  | "shipment_created"
  | "shipment_dispatched"
  | "shipment_delivered"
  | "shipment_returned"
  | "shipment_troubleshot"
  | "shipment_reassigned"
  | "manifest_closed"
  | "return_created"
  | "return_status_changed"
  | "stock_adjusted"
  | "stock_received"
  | "supplier_created"
  | "reorder_rule_updated"
  | "conversation_replied"
  | "conversation_status_changed"
  | "review_moderated"
  | "loyalty_adjusted"
  | "gift_card_issued"
  | "gift_card_cancelled"
  | "gift_card_extended"
  | "gift_card_physical_updated"
  | "gift_card_topped_up"
  | "gift_card_tier_promoted"
  | "recipe_created"
  | "recipe_updated"
  | "recipe_published"
  | "recipe_unpublished"
  | "recipe_deleted"
  | "franchise_application_received"
  | "franchise_status_changed"
  | "push_broadcast_sent"
  | "push_subscriptions_pruned"
  | "business_settings_updated"
  | "homepage_seo_updated"
  | "invoice_issued"
  | "tea_pass_interest"
  | "partner_interest"
  | "nudge_settings_updated"
  | "nudge_shown"
  | "nudge_converted";

export type ActivityActor = "admin" | "copilot" | "system";

export const adminActivityLogTable = pgTable("admin_activity_log", {
  id: serial("id").primaryKey(),
  kind: text("kind").$type<ActivityKind>().notNull(),
  actor: text("actor").$type<ActivityActor>().notNull().default("admin"),
  title: text("title").notNull(),
  summary: text("summary").notNull().default(""),
  entityType: text("entity_type"),
  entityId: text("entity_id"),
  payload: jsonb("payload")
    .$type<Record<string, unknown>>()
    .notNull()
    .default({}),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type AdminActivityLogRow =
  typeof adminActivityLogTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Customer 360 — admin-only notes attached to a customer (keyed by email).
//
// We deliberately key off email rather than shopper_user_id because some
// customers exist only as guest checkouts (orders.customer_email) and have
// no shopper account. Email is the natural join key the rest of the
// system already uses (orders, newsletter, loyalty lookup by shopper).
// ──────────────────────────────────────────────────────────────────────────

export const customerNotesTable = pgTable("customer_notes", {
  id: serial("id").primaryKey(),
  customerEmail: text("customer_email").notNull(),
  body: text("body").notNull(),
  pinned: boolean("pinned").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type CustomerNoteRow = typeof customerNotesTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Admin team — multi-operator support. The ADMIN_PASSWORD env var continues
// to work as the implicit "owner" login (single-tenant escape hatch); this
// table layers named team members on top so writes can be attributed.
//
// Roles:
//   owner  — full control + can manage other owners
//   admin  — full control except managing owners
//   staff  — read-only of admin surfaces (display-only, enforced in UI)
//
// Invite flow uses a one-time token (no email infra required); the inviter
// shares the accept link out-of-band.
// ──────────────────────────────────────────────────────────────────────────

export type AdminRole = "owner" | "admin" | "staff";
export type AdminStatus = "active" | "invited" | "revoked";

export const adminUsersTable = pgTable("admin_users", {
  id: serial("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name").notNull().default(""),
  role: text("role").notNull().default("staff").$type<AdminRole>(),
  status: text("status").notNull().default("invited").$type<AdminStatus>(),
  passwordHash: text("password_hash"),
  inviteToken: text("invite_token"),
  inviteExpiresAt: timestamp("invite_expires_at", { withTimezone: true }),
  invitedByEmail: text("invited_by_email"),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type AdminUserRow = typeof adminUsersTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Shipping & fulfilment
//
// State machine for a shipment row:
//   pending  → manifested → in_transit → out_for_delivery → delivered
//                                      ↘ delayed (sticky flag, can recover)
//                                      ↘ undelivered (attempt failed)
//                                      ↘ returned (RTO completed)
//                                      ↘ lost (manual write-off)
//
// Couriers are pluggable — the courier_code column is a free-form string
// (e.g. "delhivery", "shiprocket", "bluedart", "manual"). The courier
// client in lib/courier.ts owns the actual API integration; for now it
// returns a deterministic mock AWB so the rest of the surface is real.
// ──────────────────────────────────────────────────────────────────────────

export type ShipmentStatus =
  | "pending"
  | "manifested"
  | "in_transit"
  | "out_for_delivery"
  | "delivered"
  | "delayed"
  | "undelivered"
  | "returned"
  | "lost";

export const shippingManifestsTable = pgTable("shipping_manifests", {
  id: serial("id").primaryKey(),
  courierCode: text("courier_code").notNull(),
  status: text("status").notNull().default("open"), // open | closed
  shipmentCount: integer("shipment_count").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  closedAt: timestamp("closed_at", { withTimezone: true }),
  closedByEmail: text("closed_by_email"),
});
export type ShippingManifestRow =
  typeof shippingManifestsTable.$inferSelect;

export const shipmentsTable = pgTable("shipments", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id")
    .notNull()
    .references(() => ordersTable.id, { onDelete: "cascade" }),
  courierCode: text("courier_code").notNull(),
  awb: text("awb"),
  status: text("status").notNull().default("pending").$type<ShipmentStatus>(),
  weightGrams: integer("weight_grams").notNull().default(500),
  lengthCm: integer("length_cm").notNull().default(20),
  widthCm: integer("width_cm").notNull().default(15),
  heightCm: integer("height_cm").notNull().default(10),
  declaredValue: integer("declared_value").notNull().default(0),
  labelUrl: text("label_url"),
  trackingUrl: text("tracking_url"),
  manifestId: integer("manifest_id").references(
    () => shippingManifestsTable.id,
    { onDelete: "set null" },
  ),
  shippedAt: timestamp("shipped_at", { withTimezone: true }),
  deliveredAt: timestamp("delivered_at", { withTimezone: true }),
  lastEventAt: timestamp("last_event_at", { withTimezone: true }),
  expectedDeliveryAt: timestamp("expected_delivery_at", { withTimezone: true }),
  notes: text("notes"),
  reassignReason: text("reassign_reason"),
  reassignedFromCourier: text("reassigned_from_courier"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
}, (t) => ({
  // One shipment per order. Auto-dispatch (cron + manual) and the manual
  // create-shipment endpoint all rely on this for race-free idempotency:
  // duplicate inserts hit ON CONFLICT DO NOTHING and silently no-op.
  orderUq: uniqueIndex("shipments_order_id_uq").on(t.orderId),
}));
export type ShipmentRow = typeof shipmentsTable.$inferSelect;

export const shipmentEventsTable = pgTable("shipment_events", {
  id: serial("id").primaryKey(),
  shipmentId: integer("shipment_id")
    .notNull()
    .references(() => shipmentsTable.id, { onDelete: "cascade" }),
  kind: text("kind").notNull(), // status_changed | tracking_update | manual_note | troubleshoot
  status: text("status"), // optional shipment status snapshot
  message: text("message").notNull(),
  location: text("location"),
  source: text("source").notNull().default("admin"), // admin | courier_webhook | system
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type ShipmentEventRow = typeof shipmentEventsTable.$inferSelect;

// Returns / RMA — separate from shipments so a customer can return any
// past order regardless of whether it was originally trackable.

export type ReturnStatus =
  | "requested"
  | "approved"
  | "in_transit"
  | "received"
  | "refunded"
  | "rejected";

export const returnsTable = pgTable("returns", {
  id: serial("id").primaryKey(),
  orderId: integer("order_id")
    .notNull()
    .references(() => ordersTable.id, { onDelete: "cascade" }),
  shipmentId: integer("shipment_id").references(() => shipmentsTable.id, {
    onDelete: "set null",
  }),
  reason: text("reason").notNull(),
  notes: text("notes"),
  status: text("status").notNull().default("requested").$type<ReturnStatus>(),
  refundAmount: integer("refund_amount").notNull().default(0),
  pickupAwb: text("pickup_awb"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type ReturnRow = typeof returnsTable.$inferSelect;

// Singleton settings row controlling automated dispatch behaviour.
// We always read/write id=1 so the UI sees one rule set.
export const dispatchSettingsTable = pgTable("dispatch_settings", {
  id: integer("id").primaryKey().default(1),
  enabled: boolean("enabled").notNull().default(false),
  // Ordered preference; first courier in the list that's available + within
  // weight cap is chosen. Stored as text[] for portability.
  courierPriority: jsonb("courier_priority")
    .$type<string[]>()
    .notNull()
    .default(sql`'["delhivery","xpressbees","bluedart"]'::jsonb`),
  maxWeightGrams: integer("max_weight_grams").notNull().default(10_000),
  // Only auto-dispatch orders in this status. "paid" is the safe default.
  onlyOrderStatus: text("only_order_status").notNull().default("paid"),
  runEveryMinutes: integer("run_every_minutes").notNull().default(15),
  lastRunAt: timestamp("last_run_at", { withTimezone: true }),
  lastRunCount: integer("last_run_count").notNull().default(0),
  lastRunError: text("last_run_error"),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type DispatchSettingsRow = typeof dispatchSettingsTable.$inferSelect;

export const dispatchRunsTable = pgTable("dispatch_runs", {
  id: serial("id").primaryKey(),
  trigger: text("trigger").notNull(), // cron | manual | api
  shipmentsCreated: integer("shipments_created").notNull().default(0),
  errorMessage: text("error_message"),
  startedAt: timestamp("started_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  details: jsonb("details").$type<{ orderIds?: number[]; shipmentIds?: number[] }>(),
});
export type DispatchRunRow = typeof dispatchRunsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Inventory & stock
// We keep the canonical stock value on products.variants[].stock (existing
// behaviour) and layer audit + supply ops on top: every change writes a
// stock_movements row, suppliers + reorder_rules drive low-stock alerts.
// ──────────────────────────────────────────────────────────────────────────

export const suppliersTable = pgTable("suppliers", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  contactName: text("contact_name"),
  email: text("email"),
  phone: text("phone"),
  // How long after a PO they typically deliver — feeds reorder timing.
  leadTimeDays: integer("lead_time_days").notNull().default(7),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type SupplierRow = typeof suppliersTable.$inferSelect;

export type StockMovementKind =
  | "receive" // stock arrived (PO, manual receipt)
  | "adjust" // manual correction (cycle count, damage)
  | "sale" // order paid → decrement
  | "return" // customer return received → increment
  | "reserve" // soft-reservation (not implemented yet, future use)
  | "release"; // un-reserve

export const stockMovementsTable = pgTable("stock_movements", {
  id: serial("id").primaryKey(),
  productId: text("product_id")
    .notNull()
    .references(() => productsTable.id, { onDelete: "cascade" }),
  // Which variant.size this movement applies to. Variants live in jsonb so
  // we store the size string rather than a foreign key.
  variantSize: text("variant_size").notNull(),
  // Positive = stock added, negative = stock removed. Always signed.
  delta: integer("delta").notNull(),
  kind: text("kind").notNull().$type<StockMovementKind>(),
  reason: text("reason"),
  // Optional pointer back to source (order, return, supplier PO, etc.).
  refType: text("ref_type"),
  refId: text("ref_id"),
  createdBy: text("created_by").notNull().default("system"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type StockMovementRow = typeof stockMovementsTable.$inferSelect;

export const reorderRulesTable = pgTable(
  "reorder_rules",
  {
    id: serial("id").primaryKey(),
    productId: text("product_id")
      .notNull()
      .references(() => productsTable.id, { onDelete: "cascade" }),
    variantSize: text("variant_size").notNull(),
    // When stock falls at or below this number we surface a low-stock alert.
    minStock: integer("min_stock").notNull().default(10),
    // Suggested reorder quantity (used in the "create PO" workflow).
    reorderQty: integer("reorder_qty").notNull().default(50),
    supplierId: integer("supplier_id").references(() => suppliersTable.id, {
      onDelete: "set null",
    }),
    enabled: boolean("enabled").notNull().default(true),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // One rule per product/variant combo so the low-stock query is unambiguous.
    productVariantUq: uniqueIndex("reorder_rules_product_variant_uq").on(
      t.productId,
      t.variantSize,
    ),
  }),
);
export type ReorderRuleRow = typeof reorderRulesTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Wholesale accounts — approved B2B buyers with custom pricing tier and
// payment terms. Leads (wholesale_leads) become accounts after admin
// approval; accounts can place orders at the configured discount.
// ──────────────────────────────────────────────────────────────────────────

export type WholesaleTier = "bronze" | "silver" | "gold" | "platinum";
export type WholesalePaymentTerms = "prepaid" | "net15" | "net30" | "net45";
export type WholesaleAccountStatus = "active" | "suspended" | "closed";

export const wholesaleAccountsTable = pgTable("wholesale_accounts", {
  id: serial("id").primaryKey(),
  // Optional link back to the lead row this account was promoted from.
  leadId: integer("lead_id").references(() => wholesaleLeadsTable.id, {
    onDelete: "set null",
  }),
  companyName: text("company_name").notNull(),
  contactName: text("contact_name").notNull(),
  email: text("email").notNull().unique(),
  phone: text("phone").notNull(),
  gstin: text("gstin"),
  billingAddress: jsonb("billing_address").$type<{
    line1: string;
    line2?: string;
    city: string;
    state?: string;
    postalCode: string;
    country: string;
  }>(),
  tier: text("tier").$type<WholesaleTier>().notNull().default("bronze"),
  // Percentage off retail (0–80). Drives quote pricing and order discount.
  discountPct: integer("discount_pct").notNull().default(15),
  paymentTerms: text("payment_terms")
    .$type<WholesalePaymentTerms>()
    .notNull()
    .default("prepaid"),
  // Credit limit in paise. 0 means no credit (prepaid only).
  creditLimitPaise: integer("credit_limit_paise").notNull().default(0),
  outstandingPaise: integer("outstanding_paise").notNull().default(0),
  status: text("status")
    .$type<WholesaleAccountStatus>()
    .notNull()
    .default("active"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type WholesaleAccountRow = typeof wholesaleAccountsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Customer messaging hub — unified inbox for support conversations across
// channels. A conversation is a thread; messages are the individual posts.
// Optionally linked to a shopper user and/or an order for context.
// ──────────────────────────────────────────────────────────────────────────

export type ConversationStatus = "open" | "pending" | "resolved" | "spam";
export type ConversationChannel = "web" | "email" | "whatsapp" | "instagram";
export type ConversationPriority = "low" | "normal" | "high" | "urgent";

export const conversationsTable = pgTable("conversations", {
  id: serial("id").primaryKey(),
  shopperUserId: text("shopper_user_id").references(() => shopperUsersTable.id, {
    onDelete: "set null",
  }),
  // Snapshot of contact info at the time of creation (so unauthenticated
  // contact-form submissions still have something to display).
  contactName: text("contact_name").notNull().default(""),
  contactEmail: text("contact_email").notNull().default(""),
  subject: text("subject").notNull().default(""),
  channel: text("channel")
    .$type<ConversationChannel>()
    .notNull()
    .default("web"),
  status: text("status")
    .$type<ConversationStatus>()
    .notNull()
    .default("open"),
  priority: text("priority")
    .$type<ConversationPriority>()
    .notNull()
    .default("normal"),
  assignedAdminId: integer("assigned_admin_id").references(
    () => adminUsersTable.id,
    { onDelete: "set null" },
  ),
  // Optional order context (e.g. "Where's my order?")
  orderId: integer("order_id"),
  unreadByAdmin: boolean("unread_by_admin").notNull().default(true),
  lastMessageAt: timestamp("last_message_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  lastMessagePreview: text("last_message_preview").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type ConversationRow = typeof conversationsTable.$inferSelect;

export type MessageSender = "customer" | "admin" | "system";

export const conversationMessagesTable = pgTable("conversation_messages", {
  id: serial("id").primaryKey(),
  conversationId: integer("conversation_id")
    .notNull()
    .references(() => conversationsTable.id, { onDelete: "cascade" }),
  sender: text("sender").$type<MessageSender>().notNull(),
  // Display name for the sender (admin name, customer name, or "System").
  senderName: text("sender_name").notNull().default(""),
  // FK to admin user when sender = "admin" — useful for activity attribution.
  adminUserId: integer("admin_user_id").references(() => adminUsersTable.id, {
    onDelete: "set null",
  }),
  body: text("body").notNull(),
  // Internal admin notes are not shown to the customer.
  isInternal: boolean("is_internal").notNull().default(false),
  attachments: jsonb("attachments")
    .$type<{ url: string; name: string; size?: number }[]>()
    .notNull()
    .default([]),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type ConversationMessageRow =
  typeof conversationMessagesTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// Trend Pipeline — admin-configurable trend ingestion
// ──────────────────────────────────────────────────────────────────────────

export type TrendSourceKind =
  | "rss"
  | "reddit"
  | "google_trends"
  | "youtube"
  | "serpapi"
  | "twitter";

export const trendSourcesTable = pgTable("trend_sources", {
  id: serial("id").primaryKey(),
  kind: text("kind").$type<TrendSourceKind>().notNull(),
  // Friendly display name e.g. "World Tea News", "r/tea", "Google Trends IN".
  name: text("name").notNull(),
  // For rss: feed URL. For reddit: subreddit (e.g. "tea"). For google_trends: geo (e.g. "IN", "US").
  // For youtube/serpapi: query string. For twitter: query.
  url: text("url").notNull().default(""),
  // Optional: comma-separated allow-list keywords to filter results.
  filterKeywords: text("filter_keywords").notNull().default(""),
  // 0–10 weight applied to the score of every topic from this source.
  weight: integer("weight").notNull().default(5),
  enabled: boolean("enabled").notNull().default(true),
  lastFetchedAt: timestamp("last_fetched_at", { withTimezone: true }),
  lastError: text("last_error").notNull().default(""),
  itemsLastRun: integer("items_last_run").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export const insertTrendSourceSchema = createInsertSchema(trendSourcesTable).omit({
  id: true,
  createdAt: true,
  lastFetchedAt: true,
  lastError: true,
  itemsLastRun: true,
});
export type InsertTrendSource = z.infer<typeof insertTrendSourceSchema>;
export type TrendSourceRow = typeof trendSourcesTable.$inferSelect;

export const trendingTopicsTable = pgTable(
  "trending_topics",
  {
    id: serial("id").primaryKey(),
    // Free-text topic / headline pulled from the source.
    topic: text("topic").notNull(),
    // Normalised lowercase slug used for dedup.
    topicKey: text("topic_key").notNull(),
    sourceId: integer("source_id").references(() => trendSourcesTable.id, {
      onDelete: "set null",
    }),
    sourceKind: text("source_kind").$type<TrendSourceKind>().notNull(),
    sourceName: text("source_name").notNull().default(""),
    rawUrl: text("raw_url").notNull().default(""),
    summary: text("summary").notNull().default(""),
    tags: jsonb("tags").$type<string[]>().notNull().default([]),
    // Viral social hashtags (with # prefix) extracted from the source — passed
    // straight through to AI content prompts and rendered on the storefront.
    hashtags: jsonb("hashtags").$type<string[]>().notNull().default([]),
    // Composite score (source weight * recency * popularity hints).
    score: doublePrecision("score").notNull().default(0),
    // Flag set true when a content cron has consumed this topic.
    used: boolean("used").notNull().default(false),
    usedAt: timestamp("used_at", { withTimezone: true }),
    // Operator can dismiss noisy topics; dismissed ones never feed crons.
    dismissed: boolean("dismissed").notNull().default(false),
    fetchedAt: timestamp("fetched_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    topicKeyIdx: uniqueIndex("trending_topics_topic_key_idx").on(t.topicKey),
  }),
);
export type TrendingTopicRow = typeof trendingTopicsTable.$inferSelect;

// Single-row key/value config bag for the trend pipeline.
export const trendConfigTable = pgTable("trend_config", {
  key: text("key").primaryKey(),
  value: jsonb("value").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type TrendConfigRow = typeof trendConfigTable.$inferSelect;

// Admin-managed integration credentials (X/Twitter, YouTube, SerpAPI, Resend,
// VAPID push, Shiprocket, etc). Stored plain text behind admin-only access;
// never echoed back to the client (the API masks values on read).
export const integrationCredentialsTable = pgTable("integration_credentials", {
  key: text("key").primaryKey(),
  value: text("value").notNull().default(""),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
export type IntegrationCredentialRow = typeof integrationCredentialsTable.$inferSelect;

// ──────────────────────────────────────────────────────────────────────────
// SEO powerhouse: targeted-keyword links to entities (extends the existing
// global keywordsTable by mapping a tracked keyword to a specific
// product/article/teapedia/recipe/content-hub entity), backlink ledger,
// outreach pipeline, and per-entity AI audit runs.
// ──────────────────────────────────────────────────────────────────────────

export type SeoEntityKind = "product" | "article" | "teapedia" | "recipe" | "content-hub";

export const seoKeywordTargetsTable = pgTable(
  "seo_keyword_targets",
  {
    id: serial("id").primaryKey(),
    keywordId: integer("keyword_id")
      .notNull()
      .references(() => keywordsTable.id, { onDelete: "cascade" }),
    entityKind: text("entity_kind").$type<SeoEntityKind>().notNull(),
    entityRef: text("entity_ref").notNull(),
    intent: text("intent")
      .$type<"informational" | "commercial" | "transactional" | "navigational">()
      .notNull()
      .default("informational"),
    priority: integer("priority").notNull().default(3),
    notes: text("notes").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    uniqueTarget: uniqueIndex("seo_keyword_targets_uq").on(
      t.keywordId,
      t.entityKind,
      t.entityRef,
    ),
  }),
);
export type SeoKeywordTargetRow = typeof seoKeywordTargetsTable.$inferSelect;

export const seoBacklinksTable = pgTable(
  "seo_backlinks",
  {
    id: serial("id").primaryKey(),
    sourceUrl: text("source_url").notNull(),
    sourceDomain: text("source_domain").notNull(),
    targetUrl: text("target_url").notNull(),
    anchor: text("anchor").notNull().default(""),
    domainAuthority: integer("domain_authority"),
    status: text("status")
      .$type<"live" | "lost" | "pending" | "nofollow">()
      .notNull()
      .default("pending"),
    notes: text("notes").notNull().default(""),
    firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).notNull().defaultNow(),
    lastCheckedAt: timestamp("last_checked_at", { withTimezone: true }),
  },
  (t) => ({
    uniqueSrcTarget: uniqueIndex("seo_backlinks_src_target_uq").on(t.sourceUrl, t.targetUrl),
  }),
);
export type SeoBacklinkRow = typeof seoBacklinksTable.$inferSelect;

export const seoOutreachTable = pgTable("seo_outreach", {
  id: serial("id").primaryKey(),
  prospectDomain: text("prospect_domain").notNull(),
  contactName: text("contact_name").notNull().default(""),
  contactEmail: text("contact_email").notNull().default(""),
  angle: text("angle").notNull().default(""),
  ourUrl: text("our_url").notNull().default(""),
  status: text("status")
    .$type<"prospect" | "contacted" | "replied" | "secured" | "lost">()
    .notNull()
    .default("prospect"),
  draft: text("draft").notNull().default(""),
  lastTouchedAt: timestamp("last_touched_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
export type SeoOutreachRow = typeof seoOutreachTable.$inferSelect;

export const seoAuditRunsTable = pgTable(
  "seo_audit_runs",
  {
    id: serial("id").primaryKey(),
    entityKind: text("entity_kind").$type<SeoEntityKind>().notNull(),
    entityRef: text("entity_ref").notNull(),
    score: integer("score").notNull(),
    breakdown: jsonb("breakdown").$type<Record<string, number>>().notNull().default({}),
    issues: jsonb("issues").$type<Array<{ code: string; severity: string; message: string; fix?: string }>>().notNull().default([]),
    suggestions: jsonb("suggestions").$type<Array<{ label: string; field: string; before?: string; after: string }>>().notNull().default([]),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    entityHistoryIdx: index("seo_audit_runs_entity_history_idx").on(
      t.entityKind,
      t.entityRef,
      t.createdAt,
    ),
  }),
);
export type SeoAuditRunRow = typeof seoAuditRunsTable.$inferSelect;
